version: '3'

services:
  pdf-to-word:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - pdf-data:/app/data
    restart: unless-stopped

volumes:
  pdf-data: